// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhomqccxumwmabuzmpuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpob21xY2N4dW13bWFidXptcHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MjkwMjEsImV4cCI6MjA3NTAwNTAyMX0.wSkgKqSVNSIXTC0PEub2sfL94n9OyKFUqzHVRJoCu1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});